# About 

This notebook demonstrates neural networks (NN) classifiers, which are provided by __Reproducible experiment platform (REP)__ package. <br /> REP contains wrappers for following NN libraries:
* __theanets__
* __neurolab__ 
* __pybrain__ 


### In this notebook we show: 
* train classifier
* get predictions 
* measure quality
* pretraining and partial fitting
* combine classifiers using meta-algorithms

Most of this is done in the same way as for other classifiers (see notebook [01-howto-Classifiers.ipynb](https://github.com/yandex/rep/blob/master/howto/01-howto-Classifiers.ipynb))

# Loading data

In [1]:
import numpy, pandas
from rep.utils import train_test_split
from sklearn.metrics import roc_auc_score

sig_data = pandas.read_csv('toy_datasets/toyMC_sig_mass.csv', sep='\t')
bck_data = pandas.read_csv('toy_datasets/toyMC_bck_mass.csv', sep='\t')

labels = numpy.array([1] * len(sig_data) + [0] * len(bck_data))
data = pandas.concat([sig_data, bck_data])

### First rows of our data

In [2]:
data[:5]

CDF1      CDF2      CDF3   DOCAone  DOCAthree   DOCAtwo  \
0  1.000000  1.000000  1.000000  0.111337   0.012695  0.123426   
1  0.759755  0.597375  0.389256  0.021781   0.094551  0.088421   
2  1.000000  0.796142  0.566286  0.011852   0.004400  0.009153   
3  0.716397  0.524712  0.279033  0.015171   0.083900  0.069127   
4  1.000000  0.996479  0.888159  0.005547   0.070438  0.064689   

   FlightDistance  FlightDistanceError  Hlt1Dec  Hlt2Dec   ...         p1_IP  \
0      162.650955             0.870942        0        0   ...     11.314665   
1        4.193265             1.262280        0        0   ...      0.720070   
2        1.580610             0.261697        0        0   ...      0.362181   
3        7.884569             1.310151        0        0   ...      0.753449   
4       -2.267649             0.139555        0        0   ...      0.589455   

    p1_IPSig  p1_Laura_IsoBDT       p1_pt     p2_IP   p2_IPSig  \
0  83.196968        -0.223668  699.066467  9.799975  64.790207   
1   7.237868        -0.256142  587.628935  0.882111   8.834325   
2   4.173097        -0.252788  802.746495  0.427290   5.008959   
3   6.615949        -0.253550  564.203857  0.917409   8.695459   
4  21.869143        -0.254778  746.624928  0.388996   8.465344   

   p2_Laura_IsoBDT       p2_pt  peakingbkg           pt  
0        -0.121159  521.628174         NaN   220.742111  
1        -0.203220  532.679950         NaN   661.208843  
2        -0.409469  674.122342         NaN  1290.963982  
3        -0.192284  537.791687         NaN   692.654175  
4        -0.217319  988.539221         NaN  1328.837840  

[5 rows x 40 columns]

### Splitting into train and test

In [3]:
# Get train and test data
train_data, test_data, train_labels, test_labels = train_test_split(data, labels, train_size=0.5)

# Neural nets

All nets inherit from __sklearn.BaseEstimator__ and have the same interface as another wrappers in REP (details see in **01-howto-Classifiers**)

All of these nets libraries **support**:

* classification
* multi-classification
* regression
* multi-target regresssion
* additional fitting (using `partial_fit` method)

and **don't support**:

* staged prediction methods
* weights for data

# Variables used in training

In [4]:
variables = ["FlightDistance", "FlightDistanceError", "IP", "VertexChi2", 
             "pt", "p0_pt", "p1_pt", "p2_pt", 'LifeTime','dira']

# Theanets

In [5]:
from rep.estimators import TheanetsClassifier
print TheanetsClassifier.__doc__

Classifier from Theanets library. 

    Parameters:
    -----------
    :param features: list of features to train model
    :type features: None or list(str)
    :param layers: a sequence of values specifying the **hidden** layer configuration for the network.
        For more information please see 'Specifying layers' in theanets documentation:
        http://theanets.readthedocs.org/en/latest/creating.html#creating-specifying-layers
        Note that theanets "layers" parameter included input and output layers in the sequence as well.
    :type layers: sequence of int, tuple, dict
    :param int input_layer: size of the input layer. If equals -1, the size is taken from the training dataset
    :param int output_layer: size of the output layer. If equals -1, the size is taken from the training dataset
    :param str hidden_activation: the name of an activation function to use on hidden network layers by default
    :param str output_activation: the name of an activation function to u

### Simple training

In [6]:
tn = TheanetsClassifier(features=variables, layers=[20], 
                        trainers=[{'optimize': 'nag', 'learning_rate': 0.1}])

tn.fit(train_data, train_labels)

TheanetsClassifier(decode_from=1,
          features=['FlightDistance', 'FlightDistanceError', 'IP', 'VertexChi2', 'pt', 'p0_pt', 'p1_pt', 'p2_pt', 'LifeTime', 'dira'],
          hidden_activation='logistic', hidden_dropouts=0, hidden_noise=0,
          input_dropouts=0, input_layer=-1, input_noise=0, layers=[20],
          output_activation='linear', output_layer=-1, random_state=42,
          scaler=StandardScaler(copy=True, with_mean=True, with_std=True),
          trainers=[{'learning_rate': 0.1, 'optimize': 'nag'}])

### Predicting probabilities, measuring the quality

In [7]:
# predict probabilities for each class
prob = tn.predict_proba(test_data)
print prob

[[ 0.009143    0.990857  ]
 [ 0.4575833   0.5424167 ]
 [ 0.00761909  0.99238091]
 ..., 
 [ 0.02497847  0.97502153]
 [ 0.00605521  0.99394479]
 [ 0.00207709  0.99792291]]


In [8]:
print 'ROC AUC', roc_auc_score(test_labels, prob[:, 1])

ROC AUC 0.915042936861


### Theanets multistage training 

In some cases we need to continue training: i.e., we have new data or current trainer is not efficient anymore.

For this purpose there is `partial_fit` method, where you can continue training using different trainer or different data.

In [9]:
tn = TheanetsClassifier(features=variables, layers=[10, 10], 
                        trainers=[{'optimize': 'rprop'}])

tn.fit(train_data, train_labels)
print('training complete')

training complete


####  Second stage of fitting

In [10]:
tn.partial_fit(train_data, train_labels, **{'optimize': 'adadelta'})

TheanetsClassifier(decode_from=1,
          features=['FlightDistance', 'FlightDistanceError', 'IP', 'VertexChi2', 'pt', 'p0_pt', 'p1_pt', 'p2_pt', 'LifeTime', 'dira'],
          hidden_activation='logistic', hidden_dropouts=0, hidden_noise=0,
          input_dropouts=0, input_layer=-1, input_noise=0, layers=[10, 10],
          output_activation='linear', output_layer=-1, random_state=42,
          scaler=StandardScaler(copy=True, with_mean=True, with_std=True),
          trainers=[{'optimize': 'rprop'}, {'optimize': 'adadelta'}])

In [11]:
# predict probabilities for each class
prob = tn.predict_proba(test_data)
print prob

[[ 0.00660083  0.99339917]
 [ 0.2596483   0.7403517 ]
 [ 0.00705201  0.99294799]
 ..., 
 [ 0.07100118  0.92899882]
 [ 0.01223349  0.98776651]
 [ 0.00720634  0.99279366]]


In [12]:
print 'ROC AUC', roc_auc_score(test_labels, prob[:, 1])

ROC AUC 0.923150975008


### Predictions of classes

In [13]:
tn.predict(test_data)

array([1, 1, 1, ..., 1, 1, 1])

## Neurolab

In [14]:
from rep.estimators import NeurolabClassifier
print NeurolabClassifier.__doc__

Classifier from neurolab library. 

    Parameters:
    -----------
    :param features: features used in training
    :type features: list[str] or None
    :param list[int] layers: sequence, number of units inside each **hidden** layer.
    :param string net_type: type of network
        One of 'feed-forward', 'single-layer', 'competing-layer', 'learning-vector',
        'elman-recurrent', 'hopfield-recurrent', 'hemming-recurrent'
    :param initf: layer initializers
    :type initf: anything implementing call(layer), e.g. nl.init.* or list[nl.init.*] of shape [n_layers]
    :param trainf: net train function, default value depends on type of network
    :param scaler: transformer to apply to the input objects
    :type scaler: str or sklearn-like transformer or False (do not scale features)
    :param random_state: ignored, added for uniformity.
    :param dict kwargs: additional arguments to net __init__, varies with different net_types

    .. seealso:: https://pythonhosted.org/neur

### Let's train network using Rprop algorithm

In [15]:
import neurolab
nl = NeurolabClassifier(features=variables, layers=[10], epochs=40, trainf=neurolab.train.train_rprop)
nl.fit(train_data, train_labels)
print('training complete')

The maximum number of train epochs is reached
training complete


### After training neural network you still can improve it by using partial fit on other data:
```
nl.partial_fit(new_train_data, new_train_labels)
```


### Predict probabilities and estimate quality

In [16]:
# predict probabilities for each class
prob = nl.predict_proba(test_data)
print prob

[[ 0.02649707  0.97350293]
 [ 0.18057498  0.81942502]
 [ 0.30664611  0.69335389]
 ..., 
 [ 0.38033892  0.61966108]
 [ 0.02655342  0.97344658]
 [ 0.03700924  0.96299076]]


In [17]:
print 'ROC AUC', roc_auc_score(test_labels, prob[:, 1])

ROC AUC 0.843789454483


In [18]:
# predict labels
nl.predict(test_data)

array([1, 1, 1, ..., 1, 1, 1])

## Pybrain

In [19]:
from rep.estimators import PyBrainClassifier
print PyBrainClassifier.__doc__

Implements classification from PyBrain library 

    Parameters:
    -----------
    :param features: features used in training.
    :type features: list[str] or None
    :param scaler: transformer to apply to the input objects
    :type scaler: str or sklearn-like transformer or False (do not scale features)
    :param bool use_rprop: flag to indicate whether we should use Rprop or SGD trainer
    :param bool verbose: print train/validation errors.
    :param random_state: ignored parameter, pybrain training isn't reproducible

    **Net parameters:**

    :param list[int] layers: indicate how many neurons in each hidden(!) layer; default is 1 hidden layer with 10 neurons
    :param list[str] hiddenclass: classes of the hidden layers; default is 'SigmoidLayer'
    :param dict params: other net parameters:
        bias and outputbias (boolean) flags to indicate whether the network should have the corresponding biases,
        both default to True;
        peepholes (boolean);
        r

In [20]:
pb = PyBrainClassifier(features=variables, layers=[10, 2], hiddenclass=['TanhLayer', 'SigmoidLayer'])
pb.fit(train_data, train_labels)
print('training complete')

training complete


### Predict probabilities and estimate quality
again, we could proceed with training and use new dataset
```
nl.partial_fit(new_train_data, new_train_labels)
```


In [21]:
prob = pb.predict_proba(test_data)
print 'ROC AUC:', roc_auc_score(test_labels, prob[:, 1])

ROC AUC: 0.908227613258


### Predict labels

In [22]:
pb.predict(test_data)

array([1, 1, 1, ..., 1, 1, 1])

## Scaling of features
initial prescaling of features is frequently crucial to get some appropriate results using neural networks.

By default, all the networks use `StandardScaler` from `sklearn`, but you can use any other transformer, say MinMax or self-written by passing appropriate value as scaler. All the networks have same support of `scaler` parameter

In [23]:
from sklearn.preprocessing import MinMaxScaler
# will use StandardScaler
NeurolabClassifier(scaler='standard')
# will use MinMaxScaler
NeurolabClassifier(scaler=MinMaxScaler())
# will not use any pretransformation of features
NeurolabClassifier(scaler=False)

NeurolabClassifier(initf=<function init_rand at 0x11799f7d0>, layers=[10],
          net_type='feed-forward', random_state=None, scaler=False,
          trainf=None)

# Advantages of common interface

Let's build an ensemble of neural networks. This will be done by bagging meta-algorithm

## Bagging over Theanets classifier (same can be done with any neural network)
in practice, one will need __many__ networks to get predictions better, then obtained by one network

In [24]:
from sklearn.ensemble import BaggingClassifier

base_tn = TheanetsClassifier(layers=[20], trainers=[{'min_improvement': 0.01}])
bagging_tn = BaggingClassifier(base_estimator=base_tn, n_estimators=3)
bagging_tn.fit(train_data[variables], train_labels)
print('training complete')

training complete


In [25]:
prob = bagging_tn.predict_proba(test_data[variables])
print 'AUC', roc_auc_score(test_labels, prob[:, 1])

AUC 0.909843637812


# Other advantages of common interface
There are many things you can do with neural networks now: 
* cloning
* getting / setting parameters as dictionaries 
* use `grid_search`, play with sizes of hidden layers and other parameters
* build pipelines (`sklearn.pipeline`)
* use hierarchical training, training on subsets
* passing over internet / train classifiers on other machines / distributed learning of ensemles


And you can replace classifiers at any moment.